### ISSUE TITLE
ContributorSpellCircleHandler crash when right clicking with iCAD.

### ISSUE THREAD

**Issue by Aquaeyes** [Dudblockman/Psipherals#10]
[crash-2021-07-08_23.23.33-server.txt](https://github.com/Dudblockman/Psipherals/files/6785665/crash-2021-07-08_23.23.33-server.txt)

When right clicking with an iCAD, the game hangs. Perhaps an incompatibility with this change made 4 months ago in Psi itself? https://github.com/Vazkii/Psi/commit/6cfcb1adeb023b9b2a77734a11e6b01bbd5af5c1

Running version 1.4.0 of Psipherals, 1.16-94 of Psi.

**Comment by Dudblockman** [comment]
Already fixed in development build, but development build also relies on unreleased Psi build so an update can't be released until Psi updates (Commit 06f7d06f3aec80bf7cec3943ad1ac361f86bb415)

**Comment by Aquaeyes** [comment]
Understood, thanks for the explanation!
