### ISSUE TITLE
Game crashes when trying to cast spells using items

### ISSUE THREAD

**Issue by Trouperton** [Dudblockman/Psipherals#11]
On Minecraft 1.16.5 with Forge 36.2.1 with the psipherals-1.4.0 version of this mod, curios-forge-1.16.5-4.0.5.2, Psi 1.16-95 and Patchouli-1.16.4-53.1 the game crashes whenever I attempt to cast a spell of any type at the moment of trying to cast it. I have tested using the sword CAD and the psimetal bow with same results.

To replicate what I have been doing:

- Start a new creative world
- Create a spell onto a standard spell bullet, I personally tried caster regeneration and attack target withering spells
- Test on standard Psi mod CAD, in all my attempts the CAD had no issues casting them
- Take the spell bullet from the Psi CAD
- Insert the spell bullet into either a Psipherals CAD or psimetal bow and try casting the spell again

I have tested this multiple times, I even created a separate profile on curseforge that had only the mods mentioned and the issue has so far had a 100% reproductility.

**Comment by Trouperton** [comment]
Just noticed another issue, it seems trying to use the sword CAD (maybe the other things too) caused the same crash and there were no spells on it and it was a plain slash at the ground and I got this error code:

> The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: vazkii.psi.common.item.ItemCAD.cast(Lnet/minecraft/world/World;Lnet/minecraft/entity/player/PlayerEntity;Lvazkii/psi/common/core/handler/PlayerDataHandler$PlayerData;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;IIFLjava/util/function/Consumer;)Z
Exit Code: -1

**Comment by Dudblockman** [comment]
The current release version of Psipherals is incompatible with Psi as Psi has had internal changes 
Will be fixed next release when I can get around to tidying up enough for release
